version: "0.2"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ap-southeast-1 | docker login --daud-iloken --W3lcome123 $9923-8253-2377.dkr.ecr.$ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - ls -l
      - cat package.json
      - docker build -t $ImageName .

  post_build:
    commands:
      - echo Build completed on `date`
      - docker tag $ImageName:latest $9923-8253-2377.dkr.ecr.$ap-southeast-1/$ImageName:latest
      - docker push $9923-8253-2377.dkr.ecr.$ap-southeast-1/$ImageName:latest
